{
  "hash": "d10f38c1dcbad75f6af8a191f7c30901",
  "result": {
    "markdown": "---\ntitle: \"Data Wrangling\"\nauthor: \"Fadel Victor Shanaa\"\n---\n\n\nChallenge \n\n**Patents offer a great opportunity for data analysis, because the data is public. PatentsView is one of USPTO’s (United States Patent and Trademark Office) new initiatives**\n**intended to increase the usability and value of patent data**\n\n**Please note, that the patent data provided by the USPTO is a very large data set that might overload your computer power. Therefore, we also provide a reduced data set that is filtered to the year 2014 only with less columns, so you are able to complete the task, if your computer can’t process the large original data file.** \n\n**Alternative 1: The original USPTO data can be downloaded here:**\nhttps://patentsview.org/download/data-download-tables\n\n**Alternative 2: The reduced data set for the year 2014 can be downloaded here.**\nhttps://cloud.tuhh.de/index.php/s/sGZKmdfLfdZBFK9\n\n\n**Information about the data will be found here:**\nPatents_DB_dictionary_bulk_downloads.xlsx \n\n**1) Patent Dominance: What US company / corporation has the most patents? List the 10 US companies with the most assigned/granted patents.**\n\n**2) Recent patent activity: What US company had the most patents granted in August 2014? List the top 10 companies with the most new granted patents for August 2014.**\n\n**3) Innovation in Tech: What is the most innovative tech sector? For the top 10 companies (worldwide) with the most patents, what are the top 5 USPTO tech main classes?**\n\n**Answer the question with data.table or dplyr. You will need the following tables for each question:**\n\nQuestion            Table\n   1\t     assignee,patent_assignee\n   2\t     assignee,patent_assignee,patent\n   3\t     assignee,patent_assignee,uspc\n\n**Please note, that it is better to not upload the tables to your github repo due to their size.**\n\n\n::: {.cell hash='03_data_wrangling_cache/html/unnamed-chunk-1_036f8fbb508a485ce772cd924d05259c'}\n\n```{.r .cell-code}\n# Data Wrangling\n\n# Import libraries\nlibrary(data.table)\nlibrary(knitr)\n\n# Import data\nassignee <- fread(\"C:\\\\Users\\\\fvsha\\\\Documents\\\\GitHub\\\\ss23-bdsb-VictorReaver1999\\\\patent_data_reduced\\\\assignee.tsv\")\npatent_assignee <- fread(\"C:\\\\Users\\\\fvsha\\\\Documents\\\\GitHub\\\\ss23-bdsb-VictorReaver1999\\\\patent_data_reduced\\\\patent_assignee.tsv\")\npatent <- fread(\"C:\\\\Users\\\\fvsha\\\\Documents\\\\GitHub\\\\ss23-bdsb-VictorReaver1999\\\\patent_data_reduced\\\\patent.tsv\")\nuspc <- fread(\"C:\\\\Users\\\\fvsha\\\\Documents\\\\GitHub\\\\ss23-bdsb-VictorReaver1999\\\\patent_data_reduced\\\\uspc.tsv\")\n\n\n# Question 1\n\n\n# Merge assignee and patent_assignee tables\nassignee_patent <- merge(assignee, patent_assignee, by.x = \"id\", by.y = \"assignee_id\")\n\n# Filter for US corporations only\nus_corp_patents <- assignee_patent[type == 2, .(num_patents = .N), by = organization]\n\n# Sort in descending order\nus_corp_patents <- us_corp_patents[order(-num_patents)]\n\n# Display the top 10 companies with the most patents\nus_corp_patents_10 <- us_corp_patents[1:10]\nkable(us_corp_patents_10, align=\"c\", caption=\"Top 10 US Companies by Patents\")\n```\n\n::: {.cell-output-display}\nTable: Top 10 US Companies by Patents\n\n|                organization                 | num_patents |\n|:-------------------------------------------:|:-----------:|\n| International Business Machines Corporation |    7547     |\n|            Microsoft Corporation            |    3165     |\n|                 Google Inc.                 |    2668     |\n|            QUALCOMM Incorporated            |    2597     |\n|                 Apple Inc.                  |    2201     |\n|          General Electric Company           |    1873     |\n|  Hewlett-Packard Development Company, L.P.  |    1638     |\n|     AT&T INTELLECTUAL PROPERTY I, L.P.      |    1625     |\n|              Intel Corporation              |    1616     |\n|     GM Global Technology Operations LLC     |    1533     |\n:::\n\n```{.r .cell-code}\n# Question 2\n\n\n# Merge the patent_assignee and patent tables\npatent_merged <- merge(patent, patent_assignee, by.x = \"id\", by.y = \"patent_id\")\n\n# Extract the year and month from the date column\npatent_merged[, `:=`(year = year(date), month = month(date))]\n\n# Filter for August 2014\npatent_aug_2014 <- patent_merged[year == 2014 & month == 8]\n\n# Merge the assignee and patent_aug_2014 tables\nassignee_patent_aug_2014 <- merge(assignee, patent_aug_2014, by.x = \"id\", by.y = \"assignee_id\")\n\n# Filter for US corporations only\nus_corp_patents_aug_2014 <- assignee_patent_aug_2014[type == 2]\n\n# Count the number of patents for each organization\nnum_patents_aug_2014 <- us_corp_patents_aug_2014[, .(num_patents = .N), by = organization]\n\n# Sort in descending order\ntop_10_patents_aug_2014 <- num_patents_aug_2014[order(-num_patents)][1:10]\n\n# Display the top 10 companies with the most patents granted in August 2014\nkable(top_10_patents_aug_2014, align=\"c\", caption=\"Top 10 US Companies by Patents in August of 2014\")\n```\n\n::: {.cell-output-display}\nTable: Top 10 US Companies by Patents in August of 2014\n\n|                organization                 | num_patents |\n|:-------------------------------------------:|:-----------:|\n| International Business Machines Corporation |     718     |\n|            Microsoft Corporation            |     337     |\n|                 Google Inc.                 |     240     |\n|            QUALCOMM Incorporated            |     223     |\n|                 Apple Inc.                  |     222     |\n|              Intel Corporation              |     159     |\n|          General Electric Company           |     148     |\n|     AT&T INTELLECTUAL PROPERTY I, L.P.      |     146     |\n|  Hewlett-Packard Development Company, L.P.  |     140     |\n|     GM Global Technology Operations LLC     |     138     |\n:::\n\n```{.r .cell-code}\n# Question 3\n\n\n# Count the number of patents for each assignee\nassignee_count <- patent_assignee[, .N, by = assignee_id]\n\n# Merge assignee and assignee_count to get the number of patents for each assignee\nassignee_count <- merge(assignee, assignee_count, by.x = \"id\", by.y = \"assignee_id\")\n\n# Filter for only the Corporations\nassignee_count <- assignee_count[type %in% c(2, 3)]\n\n# Join assignee_count and patent_assignee to get the number of patents for each US corporation/individual\npatent_count <- merge(assignee_count, patent_assignee, by.x = \"id\", by.y = \"assignee_id\")\n\n# Join patent_count and uspc to get the main class for each patent\npatent_class <- merge(patent_count, uspc, by = \"patent_id\")\n\n# Count the number of patents for each organization and sort by the number of patents\ncompany_count <- patent_class[, .N, by = c(\"type\", \"organization\")]\ncompany_count <- company_count[type %in% c(2, 3)]\ncompany_count <- company_count[order(-N)]\n\n# Select the top 10 companies\ntop_companies <- company_count[1:10]\n\n# Filter patent_class for the top 10 companies\npatent_class_top <- patent_class[patent_class$organization %in% top_companies$organization]\n\n# Count the number of patents for each main class and sort by the number of patents\nclass_count <- patent_class_top[, .N, by = mainclass_id]\nclass_count <- class_count[order(-N)]\n\n# Select the top 5 main classes\ntop_classes <- class_count[1:5]\n\n# Order the patent_class by the number of patents for each company\npatent_class_ordered <- patent_class_top[order(-patent_class_top$N), ]\n\n# Print the top 10 companies with the most patents and the top 5 main classes for these companies\nkable(top_companies, align=\"c\", caption=\"Top 10 Companies Worlwide by Total Patents\")\n```\n\n::: {.cell-output-display}\nTable: Top 10 Companies Worlwide by Total Patents\n\n| type |                organization                 |   N   |\n|:----:|:-------------------------------------------:|:-----:|\n|  2   | International Business Machines Corporation | 19056 |\n|  3   |        Samsung Electronics Co., Ltd.        | 14523 |\n|  3   |           Canon Kabushiki Kaisha            | 9467  |\n|  3   |              Sony Corporation               | 8372  |\n|  2   |            QUALCOMM Incorporated            | 7322  |\n|  2   |            Microsoft Corporation            | 7195  |\n|  3   |          Kabushiki Kaisha Toshiba           | 6957  |\n|  2   |                 Google Inc.                 | 6082  |\n|  3   |             LG Electronics Inc.             | 5694  |\n|  3   |            Panasonic Corporation            | 5641  |\n:::\n\n```{.r .cell-code}\nprint(paste(\"The 5 main USPTO classes for the Top 10 Companies Worldwide are:\", paste(top_classes$mainclass_id, collapse = \", \")))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"The 5 main USPTO classes for the Top 10 Companies Worldwide are: 257, 455, 370, 348, 709\"\n```\n:::\n:::\n\n\n*The main classes correspond to the following industries as per the USPTO:*\n\n- Mainclass_id 257: **ACTIVE SOLID-STATE DEVICES (E.G., TRANSISTORS, SOLID-STATE DIODES)**¹. This class covers devices that operate by the movement of charge carriers in solid materials, such as semiconductors. The industry related to this mainclass_id is the **electronics** industry, especially for applications involving **rectification, amplification, or switching** of electrical signals².\n- Mainclass_id 455: **TELECOMMUNICATIONS**³. This class covers devices and methods for transmitting and receiving information by electromagnetic waves, such as radio, microwave, or optical signals. The industry related to this mainclass_id is the **telecommunications** industry, especially for applications involving **wireless communication, broadcasting, or modulation** of signals.\n- Mainclass_id 370: **MULTIPLEX COMMUNICATIONS**. This class covers devices and methods for transmitting and receiving multiple signals over a single communication channel or medium, such as time division multiplexing, frequency division multiplexing, or code division multiplexing. The industry related to this mainclass_id is also the **telecommunications** industry, especially for applications involving **efficient use of bandwidth, network protocols, or error correction** of signals.\n- Mainclass_id 348: **TELEVISION**. This class covers devices and methods for transmitting and receiving images by electromagnetic waves or other means, such as video cameras, monitors, projectors, or video signal processing. The industry related to this mainclass_id is the **entertainment** industry, especially for applications involving **broadcasting, recording, or displaying** of video content.\n- Mainclass_id 709: **ELECTRICAL COMPUTERS AND DIGITAL PROCESSING SYSTEMS: MULTICOMPUTER DATA TRANSFERRING**. This class covers devices and methods for transferring data between multiple computers or processors in a networked system, such as routers, switches, servers, or distributed computing. The industry related to this mainclass_id is the **information technology** industry, especially for applications involving **data communication, network architecture, or cloud computing**.\n\nSources:\n(1) Class Schedule for Class 257 ACTIVE SOLID-STATE DEVICES (E.G .... https://www.uspto.gov/web/patents/classification/uspc257/sched257.htm.\n(2) Class Definition for Class 257 - ACTIVE SOLID-STATE DEVICES (E.G .... https://www.uspto.gov/web/patents/classification/uspc257/defs257.htm.\n(3) Class 257: ACTIVE SOLID-STATE DEVICES (E.G., TRANSISTORS, SOLID-STATE .... https://www.uspto.gov/web/offices/ac/ido/oeip/taf/moc/257.htm.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}